apiVersion: v1
kind: ConfigMap
metadata:
  name: coredns-custom
  namespace: kube-system
data:
  local-dns.server: |
    __DOMAIN__:53 {
      errors
      cache 30
      template IN A __DOMAIN__ {
        match "^(.+\.)?__DOMAIN__\.$"
        answer "{{ .Name }} 60 IN A __TRAEFIK_IP__"
        fallthrough
      }
      template IN AAAA __DOMAIN__ {
        match "^(.+\.)?__DOMAIN__\.$"
        rcode NOERROR
        fallthrough
      }
    }
