apiVersion: v1
kind: Service
metadata:
  name: authentik-ldap
  namespace: __NAMESPACE__
  annotations:
    metallb.universe.tf/loadBalancerIPs: "__LDAP_IP__"
spec:
  type: LoadBalancer
  ports:
    - name: ldap
      port: 389
      targetPort: 3389
      protocol: TCP
    - name: ldaps
      port: 636
      targetPort: 6636
      protocol: TCP
  selector:
    goauthentik.io/outpost-type: ldap
