apiVersion: v1
kind: Pod
metadata:
  name: __POD_NAME__
  namespace: __NAMESPACE__
spec:
  restartPolicy: Never
  containers:
  - name: migrator
    image: alpine:3.19
    command: ["sleep", "600"]
    volumeMounts:
    - name: config
      mountPath: /config
  volumes:
  - name: config
    persistentVolumeClaim:
      claimName: __PVC_NAME__
