apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: immich-library
  namespace: __NAMESPACE__
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: nas-storage
  resources:
    requests:
      storage: 1Ti
  volumeName: immich-data-pv
