apiVersion: v1
kind: PersistentVolume
metadata:
  name: immich-data-pv
spec:
  capacity:
    storage: 1Ti
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nas-storage
  hostPath:
    path: __CLOUD_HOSTPATH__
    type: DirectoryOrCreate
