server {
  listen 8080;

  location / {
    root /usr/share/nginx/html;
    index index.html;
    add_header Access-Control-Allow-Origin *;
  }

  location /style.json {
    alias /data/style.json;
    add_header Access-Control-Allow-Origin *;
  }

  location /data/ {
    alias /data/;
    add_header Access-Control-Allow-Origin *;
    add_header Accept-Ranges bytes;
  }

  location /assets/ {
    alias /data/basemaps-assets/;
    add_header Access-Control-Allow-Origin *;
  }

  location /js/ {
    alias /data/js/;
    add_header Access-Control-Allow-Origin *;
  }
}
